In [7]:
!pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/, https://download.pytorch.org/whl/cu113


In [8]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [1]:
from transformers import PegasusForConditionalGeneration, PegasusTokenizer

In [15]:
!pip install sentencepiece

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
tokenizer = PegasusTokenizer.from_pretrained("google/pegasus-xsum")

Downloading:   0%|          | 0.00/1.82M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/87.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.36k [00:00<?, ?B/s]

In [3]:
#loading a model
model = PegasusForConditionalGeneration.from_pretrained("google/pegasus-xsum")

Downloading:   0%|          | 0.00/2.12G [00:00<?, ?B/s]

In [4]:
text = """ 
Pakistan,[c] officially the Islamic Republic of Pakistan,[d] is a country in South Asia. It is the world's fifth-most populous country, with a population of almost 242 million, and has the world's second-largest Muslim population.[13] Pakistan is the 33rd-largest country by area, spanning 881,913 square kilometres (340,509 square miles). It has a 1,046-kilometre (650-mile) coastline along the Arabian Sea and Gulf of Oman in the south, and is bordered by India to the east, Afghanistan to the west, Iran to the southwest, and China to the northeast. It is separated narrowly from Tajikistan by Afghanistan's Wakhan Corridor in the north, and also shares a maritime border with Oman.

Pakistan is the site of several ancient cultures, including the 8,500-year-old Neolithic site of Mehrgarh in Balochistan,[14] and the Indus Valley Civilisation of the Bronze Age, the most extensive of the civilisations of the Afro-Eurasia.[15][16] The region that comprises the modern state of Pakistan was the realm of multiple empires and dynasties, including the Achaemenid; briefly that of Alexander the Great; the Seleucid, the Maurya, the Kushan, the Gupta;[17] the Umayyad Caliphate in its southern regions, the Hindu Shahis, the Ghaznavids, the Delhi Sultanate, the Mughals,[18] the Durranis, the Sikh Empire, British East India Company rule, and most recently, the British Indian Empire from 1858 to 1947.

Spurred by the Pakistan Movement, which sought a homeland for the Muslims of British India, and election victories in 1946 by the All-India Muslim League, Pakistan gained independence in 1947 after the Partition of the British Indian Empire, which awarded separate statehood to its Muslim-majority regions and was accompanied by an unparalleled mass migration and loss of life.[19] Initially a Dominion of the British Commonwealth, Pakistan officially drafted its constitution in 1956, and emerged as a declared Islamic republic. In 1971, the exclave of East Pakistan seceded as the new country of Bangladesh after a nine-month-long civil war. In the following four decades, Pakistan has been ruled by governments whose descriptions, although complex, commonly alternated between civilian and military, democratic and authoritarian, relatively secular and Islamist.[20] Pakistan elected a civilian government in 2008, and in 2010 adopted a parliamentary system with periodic elections.

"""

In [27]:
text = """
Pakistan is a regional[22][23][24] and middle power nation,[25][26][27] and has the world's sixth-largest standing armed forces. It is a declared nuclear-weapons state, and is ranked amongst the emerging and growth-leading economies,[28] with a large and rapidly-growing middle class.[29] Pakistan's political history since independence has been characterised by periods of significant economic and military growth as well as those of political and economic instability. It is an ethnically and linguistically diverse country, with similarly diverse geography and wildlife. The country continues to face challenges, including poverty, illiteracy, corruption and terrorism.[30] Pakistan is a member of the United Nations, the Shanghai Cooperation Organisation, the Organisation of Islamic Cooperation, the Commonwealth of Nations, the South Asian Association for Regional Cooperation, and the Islamic Military Counter-Terrorism Coalition, and is designated as a major non-NATO ally by the United States. 
"""

In [28]:
print("**Input Text**\n",text)

**Input Text**
 
Pakistan is a regional[22][23][24] and middle power nation,[25][26][27] and has the world's sixth-largest standing armed forces. It is a declared nuclear-weapons state, and is ranked amongst the emerging and growth-leading economies,[28] with a large and rapidly-growing middle class.[29] Pakistan's political history since independence has been characterised by periods of significant economic and military growth as well as those of political and economic instability. It is an ethnically and linguistically diverse country, with similarly diverse geography and wildlife. The country continues to face challenges, including poverty, illiteracy, corruption and terrorism.[30] Pakistan is a member of the United Nations, the Shanghai Cooperation Organisation, the Organisation of Islamic Cooperation, the Commonwealth of Nations, the South Asian Association for Regional Cooperation, and the Islamic Military Counter-Terrorism Coalition, and is designated as a major non-NATO ally by

In [29]:
#create tokens - numbers representation of our text
tokens = tokenizer(text, truncation=True, padding="longest", 
                   return_tensors='pt')

tokens

{'input_ids': tensor([[ 4856,   117,   114,  2881,  4101,  8101, 32887,  8791, 32887,  6304,
          1100,   111,  1624,   484,  2270,   108,  4101,  5247, 32887,  9965,
         32887,  9613,  1100,   111,   148,   109,   278,   131,   116,  6932,
           121, 22504,  2716,  7355,  3062,   107,   168,   117,   114,  6130,
          4573,   121, 65872,   116,   449,   108,   111,   117,  5395,  4545,
           109,  4610,   111,   874,   121, 12267, 10614,   108,  4101,  9169,
          1100,   122,   114,   423,   111,  4420,   121, 12138,  1624,   755,
           107,  4101, 10340,  1100,  4856,   131,   116,  1488,   689,   381,
          6846,   148,   174, 29383,   141,  5059,   113,  1225,  1500,   111,
          2002,   874,   130,   210,   130,   274,   113,  1488,   111,  1500,
         20868,   107,   168,   117,   142, 66773,   111, 92366,  2766,   531,
           108,   122, 10808,  2766, 14073,   111,  4809,   107,   139,   531,
          2138,   112,   749,  1628,  

In [30]:
tokens.keys()

dict_keys(['input_ids', 'attention_mask'])

In [31]:
tokens['input_ids'][0]

tensor([ 4856,   117,   114,  2881,  4101,  8101, 32887,  8791, 32887,  6304,
         1100,   111,  1624,   484,  2270,   108,  4101,  5247, 32887,  9965,
        32887,  9613,  1100,   111,   148,   109,   278,   131,   116,  6932,
          121, 22504,  2716,  7355,  3062,   107,   168,   117,   114,  6130,
         4573,   121, 65872,   116,   449,   108,   111,   117,  5395,  4545,
          109,  4610,   111,   874,   121, 12267, 10614,   108,  4101,  9169,
         1100,   122,   114,   423,   111,  4420,   121, 12138,  1624,   755,
          107,  4101, 10340,  1100,  4856,   131,   116,  1488,   689,   381,
         6846,   148,   174, 29383,   141,  5059,   113,  1225,  1500,   111,
         2002,   874,   130,   210,   130,   274,   113,  1488,   111,  1500,
        20868,   107,   168,   117,   142, 66773,   111, 92366,  2766,   531,
          108,   122, 10808,  2766, 14073,   111,  4809,   107,   139,   531,
         2138,   112,   749,  1628,   108,   330,  5360,   108, 

In [32]:
tokens['attention_mask'][0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1])

In [33]:
type({**tokens})

dict

In [34]:
#summarize
summary = model.generate(**tokens)

In [35]:
# giving the token of resultant words
summary

tensor([[    0,  4856,   117,   156,   113,   109,   278,   131,   116,   205,
           356,   111,  3908, 60190,   107,     1]])

In [36]:
#decoding 
tokenizer.decode(summary[0])

"Pakistan is one of the world's most important and stable democracies."